# -*- coding: utf-8 -*-
"""Python-Class-06-02-2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1amyxfT4L_dsAC3LTR05OWUj_wagUqcYd
"""

#Python Class 6/02/2021



#   %run car.py
#   from car import Car
#   car1 = Car()

car4 = Car4("Honda","abc",2015)

car4.get_descriptive_name()

#Files Chapter 10
with open("abc.txt","w") as obj:
  obj.write("hello Filess")

#write mood me agr file create nhi hai to file create b krega or write b krega 
with open("hello.txt","w") as obj:
  obj.write("Im another file")

with open("abc.txt","r") as f:
  line = f.readline()

line

with open("hello.txt","a") as obj:
  obj.write(" Im apend file")

